repos:
  - repo: https://github.com/MarketSquare/robocop
    rev: 6.7.0
    hooks:
      - id: robocop
        args:
          - --configure
          - reports:all
      - id: robocop-format
        name: robocop-format (Robotidy replacement)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff
        args: ["--fix"]

