*** Settings ***
Documentation       The purpose of this file is to be an index of all page object resource files. Please note that this
...                 file is not designed for performance reasons, but rather overall project convenience as you will
...                 have less files to import or reference when creating your keyword functionality.

Resource            landing_page.resource
Resource            main_page.resource
Resource            wiki_page.resource
